### ISSUE TITLE
Проблема с функциями _usb_ep_write и _usb_ep_read

### ISSUE THREAD

**Issue by karetskiiVO** [COKPOWEHEU/usb#6]
Где сборщик находит код для этих функций? С минимальными правками собираю под `stm32l152rc`
вердикт `ld` следующий(platform io):
`in function stm32::ep0_out(unsigned char):
usb.cpp:(.text._ZN5stm32L7ep0_outEh+0x28): undefined reference to _usb_ep_read(unsigned char, unsigned short*)`

**Comment by COKPOWEHEU** [comment]
В файле [usb_lib.c](https://github.com/COKPOWEHEU/usb/blob/c23a38154295175f128f517396534860f2ac05ce/1.Core_L1/src/usb_lib.c#L382), в конце.
Но, возможно, в каком-то из примеров забыл исправить. Хотя вроде проверял.
